// $(function(){
//     $("button").click(function(){
//         $("span").hide()
//     })
// })
// $(function(){
//     $("button").dblclick(function(){
//         $("span").hide()
//     })
// })
// $(function(){
//     $("button").mouseenter(function(){
//         $("span").hide()
//     })
// })
// $(function(){
//     $("button").mouseleave(function(){
//         $("span").hide()
//     })
// })